force-app/main/default/objects/Account/fields/Administration_Id__c.field-meta.xml
<CustomField>
    <fullName>Administration_Id__c</fullName>
    <description>System where this account originated</description>
    <inlineHelpText>System where this account originated</inlineHelpText>
    <label>Administration Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <complianceGroup>GDPR (Financial)</complianceGroup>
    <description>Formula to show the IBAN of the selected Default Bank Account on this Account</description>
    <formula>Default_Bank_Account__r.IBAN__c</formula>
    <label>Bank Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Chamber_Of_Commerce_Number__c.field-meta.xml
<CustomField>
    <fullName>Chamber_Of_Commerce_Number__c</fullName>
    <description>Chamber of commerce (KvK) number of this organisation</description>
    <label>Chamber Of Commerce Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Identifier from the system listed as Id administration</description>
    <externalId>true</externalId>
    <inlineHelpText>Identifier from the system listed as Id administration</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation_Type__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Type__c</fullName>
    <description>Type of organisation / Legal Form</description>
    <label>Organisation Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Address__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Address at this moment</description>
    <label>Primary Billing Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Primary Billing Address for Accounts</relationshipLabel>
    <relationshipName>Primary_Billing_Address_for_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Address__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary address record</description>
    <label>Primary Shipping Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Primary Shipping Address for Accounts</relationshipLabel>
    <relationshipName>Primary_Shipping_Address_For_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique identifier used in inbound webservices</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <complianceGroup>GDPR (Financial)</complianceGroup>
    <description>VAT Number of this organisation</description>
    <label>VAT Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction between account and address__c</description>
    <label>Klant Adres</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Klant Adressen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Address for this account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This checkbox is selected if the account address is active based on entered start and end date.</description>
    <formula>IF(
AND(Start_Date__c &lt;= TODAY(),
OR(End_Date__c &gt;= TODAY(),
ISBLANK(End_Date__c)
)
), True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This checkbox is selected if the account address is active based on entered start and end date.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Deduplication_Key__c.field-meta.xml
<CustomField>
    <fullName>Deduplication_Key__c</fullName>
    <description>Composite key to prevent duplicates</description>
    <externalId>true</externalId>
    <label>Deduplication Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Validity of this address ends at this date</description>
    <inlineHelpText>Validity of this address ends at this date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Validity of this address starts at this date</description>
    <inlineHelpText>Validity of this address starts at this date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this Account address record. Postadres corresponds with BillingAddress and Eenheid/Woonadres with ShippingAddress on Account</description>
    <inlineHelpText>Type of this Account address record. Postadres corresponds with BillingAddress and Eenheid/Woonadres with ShippingAddress on Account</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WOO</fullName>
                <label>Woonadres</label>
            </value>
            <value>
                <fullName>POS</fullName>
                <label>Postadres</label>
            </value>
            <value>
                <fullName>BUI</fullName>
                <isActive>false</isActive>
                <label>Buitenlands adres</label>
            </value>
            <value>
                <fullName>EEN</fullName>
                <isActive>false</isActive>
                <label>EEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Administration_Id__c.field-meta.xml
<CustomField>
    <fullName>Administration_Id__c</fullName>
    <description>System where this record originated</description>
    <inlineHelpText>System where this record originated</inlineHelpText>
    <label>Administration Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Deduplication_Key__c.field-meta.xml
<CustomField>
    <fullName>Deduplication_Key__c</fullName>
    <description>For allowing upserts on this object</description>
    <externalId>true</externalId>
    <label>Deduplication Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Identifier in external system</description>
    <externalId>true</externalId>
    <inlineHelpText>Identifier in external system</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;NL&quot;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>House number</description>
    <inlineHelpText>House number</inlineHelpText>
    <label>House Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PO_Box_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Box_Number__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>To register the PO Box Number</description>
    <inlineHelpText>To register the PO Box Number</inlineHelpText>
    <label>PO Box Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Street name</description>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>IBAN number for this bank account</description>
    <label>IBAN</label>
    <length>34</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Integration_Key__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key__c</fullName>
    <description>Filled by integration logic to upsert data on. Combines UUID of person, Admin Id and External Id. Assumes Bank details are readonly in SF</description>
    <externalId>true</externalId>
    <label>Integration Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subsidiary_Relation__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Relation__c</fullName>
    <complianceGroup>GDPR (Salesforce Id)</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Subsidiary personaccount or contact in this relation</description>
    <label>Subsidiary Relation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships (Subsidiary Relation)</relationshipLabel>
    <relationshipName>Subsidiary_Account_In_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PersoonService.cls
/**
 * Service class to convert SObject data to the PersoonModel structs
 */
public with sharing class PersoonService {
    public static PersoonModel getPersoonByUuid(String uuid) {
        //
        // Query the requested person + all additional data and return it
        List<Account> theAccounts = [SELECT Id, Name, Administration_Id__c, RecordType.DeveloperName, IsPersonAccount, UUID__c, External_Id__c,
                Type, Preferred_Communication_Channel__pc,
                LastName, FirstName, PersonBirthdate, PersonGenderIdentity, Salutation, Death_Date__pc, MiddleName, Initials__pc,
                PersonEmail, PersonMobilePhone, Phone, Preferred_Phone__pc,
                VAT_Number__c, Chamber_Of_Commerce_Number__c, Organisation_Type__c,
                Primary_Billing_Address__c, Primary_Shipping_Address__c,
                Primary_Shipping_Address__r.Province__c, Primary_Billing_Address__r.Province__c, Primary_Billing_Address__r.Denotation__c,
                Primary_Billing_Address__r.Unique_Key__c, Primary_Billing_Address__r.Name, Primary_Billing_Address__r.PO_Box_Number__c, Primary_Billing_Address__r.Postal_Code__c,
                Primary_Billing_Address__r.Freepost_number__c, Primary_Billing_Address__r.Street__c, Primary_Billing_Address__r.Country__c, Primary_Billing_Address__r.House_Letter__c, Primary_Billing_Address__r.Address_Line_2__c,
                Primary_Billing_Address__r.House_Number_Addition__c, Primary_Billing_Address__r.House_Number__c, Primary_Billing_Address__r.City__c, Primary_Billing_Address__r.Address_Line_1__c,
                Primary_Shipping_Address__r.Denotation__c, Primary_Shipping_Address__r.Unique_Key__c, Primary_Shipping_Address__r.Name, Primary_Shipping_Address__r.PO_Box_Number__c, Primary_Shipping_Address__r.Postal_Code__c,
                Primary_Shipping_Address__r.Freepost_number__c, Primary_Shipping_Address__r.Street__c, Primary_Shipping_Address__r.Country__c, Primary_Shipping_Address__r.House_Letter__c, Primary_Shipping_Address__r.Address_Line_2__c,
                Primary_Shipping_Address__r.House_Number_Addition__c, Primary_Shipping_Address__r.House_Number__c, Primary_Shipping_Address__r.City__c, Primary_Shipping_Address__r.Address_Line_1__c,
                (SELECT Id, IBAN__c, Valid_To__c, Valid_From__c, Bic__c, Default__c, External_Id__c, Administration_Id__c, Account__r.UUID__c, Active__c FROM Bank_Accounts__r),
                (SELECT Id, Type__c, Start_Date__c, End_Date__c, Primary_Relation__r.UUID__c, Subsidiary_Relation__r.UUID__c FROM Primary_Account_In_Relationships__r),
                (SELECT Id, Type__c, Start_Date__c, End_Date__c, Primary_Relation__r.UUID__c, Subsidiary_Relation__r.UUID__c FROM Subsidiary_Account_In_Relationships__r),
                (SELECT Id, Roles, StartDate, EndDate, Account.UUID__c, Contact.Contact_UUID__c FROM AccountContactRelations)
        FROM Account
        WHERE UUID__c = :uuid
        LIMIT 1];
        if(theAccounts <> null && theAccounts.size() == 1) {
            Account theAccount = theAccounts[0];
            PersoonModel pm = DataMapper.accountToPersoon(theAccount);
            //
            // Add the address data
            if(theAccount.Primary_Billing_Address__c <> null) {
                pm.postadres = new PersoonAdresModel();
                pm.postadres.soort = new ReferentieCodeModel();
                pm.postadres.soort.code = 'POS';
                pm.postadres.adres = DataMapper.mapAddressToAdresModel(theAccount.Primary_Billing_Address__r);
            }
            if(theAccount.Primary_Shipping_Address__c <> null) {
                pm.woonadres = new PersoonAdresModel();
                pm.woonadres.soort = new ReferentieCodeModel();
                pm.woonadres.soort.code = 'WOO';
                pm.woonadres.adres = DataMapper.mapAddressToAdresModel(theAccount.Primary_Shipping_Address__r);
            }
            //
            // Add bank account data
            if(theAccount.Bank_Accounts__r?.size() > 0) {
                pm.betaalgegevens = new List<BetaalgegevenModel>();
                for(Bank_Account__c ba : theAccount.Bank_Accounts__r) {
                    BetaalgegevenModel bmodel = DataMapper.mapBankAccountToBetaalGegevenModel(ba);
                    pm.betaalgegevens.add(bmodel);
                }
            }

            //
            // Add relations between accounts/persons
            pm.persoonRelaties = new List<PersoonRelatieModel>();

            //
            // Add relationship data for primary side
            if(theAccount.Primary_Account_In_Relationships__r?.size() > 0) {
                for(Relationship__c rel : theAccount.Primary_Account_In_Relationships__r) {
                    PersoonRelatieModel prModel = DataMapper.mapRelationShipToPersoonRelatieModel(rel);
                    pm.persoonRelaties.add(prModel);
                }
            }
            //
            // Add relationship data for subsidiary side
            if(theAccount.Subsidiary_Account_In_Relationships__r?.size() > 0) {
                for(Relationship__c rel : theAccount.Subsidiary_Account_In_Relationships__r) {
                    PersoonRelatieModel prModel = DataMapper.mapRelationShipToPersoonRelatieModel(rel);
                    pm.persoonRelaties.add(prModel);
                }
            }

            //
            // Add relationship data for other types of relations
            if(theAccount.AccountContactRelations?.size() > 0) {
                for(AccountContactRelation rel : theAccount.AccountContactRelations) {
                    PersoonRelatieModel prModel = DataMapper.mapRelationShipToPersoonRelatieModel(rel);
                    pm.persoonRelaties.add(prModel);
                }
            }

            return pm;
        } else {
            //
            // Not found
            return null;
        }
    }
    public static PersoonModel postPersoon(PersoonModel persoon) {
        try {
            //
            // Post always used for new accounts
            Account acc = DataMapper.persoonToAccount(persoon);

            //
            // Assign the UUID here, if empty
            if (String.isEmpty(acc.UUID__c)) {
                acc.UUID__c = IdentifierService.getUUID();
            }

            //
            // Ignore duplicate rules
            System.debug('### Saving account: ' + JSON.serializePretty(acc));
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true;
            Database.SaveResult sr = Database.insert(acc, dml);

            if (sr.isSuccess()) {

                //
                // Create the addresses
                List<Account_Address__c> accAddresses = AddressService.convertPersoonAddresses(persoon, acc.UUID__c);
                upsert accAddresses Schema.Account_Address__c.Deduplication_Key__c;

                //
                // Bank accounts
                List<Bank_Account__c> bas = BankAccountService.getBankAccountRecordsForUpsert(persoon, acc.UUID__c);
                //System.debug('### UPSERTING BANK ACCOUNTS '+JSON.serializePretty(bas));
                upsert bas Schema.Bank_Account__c.Integration_Key__c;

                //
                // Relations
                List<AccountContactRelation> accContactRelations = PersonRelationService.getAccountContactRelationRecordsForUpsert(persoon, acc.UUID__c);
                System.debug('### Upserting accContactRelations ' + JSON.serializePretty(accContactRelations));
                upsert accContactRelations Schema.AccountContactRelation.Deduplication_Key__c;

                List<Relationship__c> relationships = PersonRelationService.getRelationshipRecordsForUpsert(persoon, acc.UUID__c);
                System.debug('### Upserting relationships ' + JSON.serializePretty(relationships));
                upsert relationships Schema.Relationship__c.Deduplication_Key__c;

                //
                // Enrich input for output
                persoon.id = acc.UUID__c;
                return persoon;

            } else {
                ApexFaultHandler.publishError(JSON.serialize(sr.getErrors()), 'PersoonService', 'postPersoon');
                throw new PersoonServiceException(JSON.serialize(sr.getErrors()));
            }

        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'PersoonService', 'postPersoon');
            throw ex;
        }
    }
    public static PersoonModel patchPersoon(String uuid, PersoonModel persoon) {
        try {
            Account acc = DataMapper.persoonToAccount(persoon);
            acc.UUID__c = uuid;
            Database.UpsertResult sr = Database.upsert(acc, Account.fields.UUID__c);

            if(sr.isSuccess()) {
                List<Account_Address__c> accAddresses = AddressService.convertPersoonAddresses(persoon, acc.UUID__c);

                upsert accAddresses Schema.Account_Address__c.Deduplication_Key__c;
                //
                // Bank accounts
                List<Bank_Account__c> bas = BankAccountService.getBankAccountRecordsForUpsert(persoon, acc.UUID__c);
                upsert bas Schema.Bank_Account__c.Integration_Key__c;


                // Relations
                List<AccountContactRelation> accContactRelations = PersonRelationService.getAccountContactRelationRecordsForUpsert(persoon, acc.UUID__c);
                upsert accContactRelations Schema.AccountContactRelation.Deduplication_Key__c;

                List<Relationship__c> relationships = PersonRelationService.getRelationshipRecordsForUpsert(persoon, acc.UUID__c);
                upsert relationships Schema.Relationship__c.Deduplication_Key__c;

                persoon.id = acc.UUID__c;

                return persoon;
            } else {
                ApexFaultHandler.publishError(JSON.serialize(sr.getErrors()),'PersoonService','patchPersoon');
                throw new PersoonServiceException(JSON.serialize(sr.getErrors()));
            }    
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'PersoonService', 'patchPersoon');
            throw ex;
        }
    }
    //
    // Validates a PATCH body
    public static PersoonRequestValidationResult validatePatchRequest(PersoonModel patchPersoon) {
        PersoonRequestValidationResult result = new PersoonRequestValidationResult();
        result.isValid = true;
        return result;
    }
    //
    // Validates a POST body
    public static PersoonRequestValidationResult validatePostRequest(PersoonModel postPersoon) {
        System.debug('### Validating persoon: '+JSON.serializePretty(postPersoon));
        PersoonRequestValidationResult result = new PersoonRequestValidationResult();
        result.isValid = true;
        if(postPersoon == null) {
            result.isValid = false;
            result.validationErrors.add('Missing Persoon');
        } else {
            if(postPersoon.soort == null) {
                result.isValid = false;
                result.validationErrors.add('Missing Persoon Soort');
            } else {
                if(postPersoon.soort.code == null) {
                    result.isValid = false;
                    result.validationErrors.add('Missing Persoon Soort Code');
                } else {
                    if(postPersoon.soort.code=='NAT') {
                        //
                        // Last Name mandatory
                        if(postPersoon.achternaam == null) {
                            result.isValid = false;
                            result.validationErrors.add('Missing Achternaam for Natuurlijkpersoon');
                        }
                    } else if(postPersoon.soort.code=='REC') {
                        //
                        // Name mandatory
                        if(postPersoon.naam == null) {
                            result.isValid = false;
                            result.validationErrors.add('Missing Naam for Rechtspersoon');

                        }

                    }
                }
            }
        }
        return result;
    }

    public class PersoonRequestValidationResult {
        public Boolean isValid;
        public List<String> validationErrors {
            get {
                if(validationErrors == null) {
                    validationErrors =  new List<String>();
                }
                return validationErrors;
            }
            set;
        }
    }
    public class PersoonServiceException extends Exception {

    }

}