force-app/main/default/objects/Account/fields/Administration_Id__c.field-meta.xml
<CustomField>
    <fullName>Administration_Id__c</fullName>
    <description>System where this account originated</description>
    <inlineHelpText>System where this account originated</inlineHelpText>
    <label>Administration Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <complianceGroup>GDPR (Financial)</complianceGroup>
    <description>Formula to show the IBAN of the selected Default Bank Account on this Account</description>
    <formula>Default_Bank_Account__r.IBAN__c</formula>
    <label>Bank Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Identifier from the system listed as Id administration</description>
    <externalId>true</externalId>
    <inlineHelpText>Identifier from the system listed as Id administration</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique identifier used in inbound webservices</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Integration_Key__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key__c</fullName>
    <description>Filled by integration logic to upsert data on. Combines UUID of person, Admin Id and External Id. Assumes Bank details are readonly in SF</description>
    <externalId>true</externalId>
    <label>Integration Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BankAccountService.cls
/**
 * Created by harm on 27/08/2024.
 */
public with sharing class BankAccountService  {
    public static List<Bank_Account__c> getBankAccountRecordsForUpsert(PersoonModel pm, String personUuid) {
        List<Bank_Account__c> output = new List<Bank_Account__c>();
        if(pm.betaalgegevens?.size() > 0) {
            for(BetaalgegevenModel bm : pm.betaalgegevens) {
                Bank_Account__c baRecord = DataMapper.mapBetaalGegevenModelToBankAccount(bm);
                baRecord.Account__r = new Account(UUID__c=personUuid);
                baRecord.Integration_Key__c = personUuid+'-'+baRecord.Administration_Id__c+'-'+baRecord.External_Id__c;
                output.add(baRecord);
            }
        }
        return output;
    }
}