force-app/main/default/objects/Account/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <complianceGroup>GDPR (Financial)</complianceGroup>
    <description>Formula to show the IBAN of the selected Default Bank Account on this Account</description>
    <formula>Default_Bank_Account__r.IBAN__c</formula>
    <label>Bank Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Identifier from the system listed as Id administration</description>
    <externalId>true</externalId>
    <inlineHelpText>Identifier from the system listed as Id administration</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Identifier in external system</description>
    <externalId>true</externalId>
    <inlineHelpText>Identifier in external system</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Role_2__c.field-meta.xml
<CustomField>
    <fullName>Role_2__c</fullName>
    <description>Different Account Contact Relationship roles that can exist between an Account and a Contact</description>
    <inlineHelpText>What Account Contact Relationship roles can exist between an Account and a Contact?</inlineHelpText>
    <label>Role Relation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPE</fullName>
                <label>Contactpersoon</label>
            </value>
            <value>
                <fullName>MDW</fullName>
                <label>Medewerker</label>
            </value>
            <value>
                <fullName>BEH</fullName>
                <isActive>false</isActive>
                <label>Beheerder</label>
            </value>
            <value>
                <fullName>BSL</fullName>
                <isActive>false</isActive>
                <label>Bestuurslid</label>
            </value>
            <value>
                <fullName>Bewindgevoerde</fullName>
                <isActive>false</isActive>
                <label>Bewindgevoerde</label>
            </value>
            <value>
                <fullName>EIG</fullName>
                <isActive>false</isActive>
                <label>MVE Eigenaar</label>
            </value>
            <value>
                <fullName>PEN</fullName>
                <isActive>false</isActive>
                <label>Penningmeester</label>
            </value>
            <value>
                <fullName>SEC</fullName>
                <isActive>false</isActive>
                <label>Secretaris</label>
            </value>
            <value>
                <fullName>VVL</fullName>
                <isActive>false</isActive>
                <label>VVE-lid</label>
            </value>
            <value>
                <fullName>VOO</fullName>
                <isActive>false</isActive>
                <label>Voorzitter</label>
            </value>
            <value>
                <fullName>Werkgever</fullName>
                <isActive>false</isActive>
                <label>Werkgever</label>
            </value>
            <value>
                <fullName>WOL</fullName>
                <isActive>false</isActive>
                <label>Wooncommissie lid</label>
            </value>
            <value>
                <fullName>COL</fullName>
                <isActive>false</isActive>
                <label>Wooncoöperatielid</label>
            </value>
            <value>
                <fullName>ccc</fullName>
                <isActive>false</isActive>
                <label>ccc</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;NL&quot;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>House number</description>
    <inlineHelpText>House number</inlineHelpText>
    <label>House Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Street name</description>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>IBAN number for this bank account</description>
    <label>IBAN</label>
    <length>34</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subsidiary_Relation__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Relation__c</fullName>
    <complianceGroup>GDPR (Salesforce Id)</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Subsidiary personaccount or contact in this relation</description>
    <label>Subsidiary Relation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships (Subsidiary Relation)</relationshipLabel>
    <relationshipName>Subsidiary_Account_In_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
 * Generates test data
 */
public with sharing class TestDataFactory {
    public static List<Account> getPersonAccounts(Integer numberOfAccounts) {
        RecordType rt = [SELECT Id FROM RecordType WHERE IsPersonType=true AND SobjectType='Account' AND IsActive=true LIMIT 1];

        List<Account> output = new List<Account>();
        for(Integer x=0; x <numberOfAccounts; x++) {
            Account acc = new Account();
            acc.LastName = 'Test Acc '+x;
            acc.FirstName = 'Person';
            acc.RecordTypeId = rt.Id;
            output.add(acc);
        }
        return output;
    }
    public static List<Account> getBusinessAccounts(Integer numberOfAccounts) {
        RecordType rt = [SELECT Id FROM RecordType WHERE IsPersonType=false AND SobjectType='Account' AND IsActive=true LIMIT 1];

        List<Account> output = new List<Account>();
        for(Integer x=0; x <numberOfAccounts; x++) {
            Account acc = new Account();
            acc.Name = 'Test Acc '+x;
            acc.RecordTypeId = rt.Id;
            output.add(acc);
        }
        return output;
    }
    public static List<Address__c> getAddresses(Integer numberAddresses) {

        List<Address__c> output = new List<Address__c>();
        for(Integer x=0; x <numberAddresses; x++) {
            Address__c addr = new Address__c();
            addr.Street__c = 'Street'+x;
            addr.Postal_Code__c = '123'+x+'AA';
            addr.Country__c = 'NL';
            addr.House_Letter__c = 'a';
            addr.House_Number__c = String.valueOf(x);
            addr.City__c = 'Apexia';
            addr.Unique_Key__c = AddressService.getAddressKey(addr);
            addr.Name = AddressService.getNameValue(addr);
            output.add(addr);
        }
        return output;
    }
    public static List<Bank_Account__c> getBankAccounts(Integer numBankAccounts, ID accountId) {

        List<Bank_Account__c> output = new List<Bank_Account__c>();
        for(Integer x=0; x <numBankAccounts; x++) {
            Bank_Account__c bacc = new Bank_Account__c();
            bacc.Account__c = accountId;
            bacc.IBAN__c = 'NL73RABO0447391550';
            output.add(bacc);
        }
        return output;
    }
    public static Relationship__c getRelationship(Id primaryId, Id subsidiaryId, String type) {
        Relationship__c rl = new Relationship__c();
        rl.Primary_Relation__c = primaryId;
        rl.Subsidiary_Relation__c = subsidiaryId;
        rl.Type__c = type;
        return rl;
    }
    public static AccountContactRelation getAccountContactRelationship(Id accountId, Id contactId, String type) {
        AccountContactRelation rl = new AccountContactRelation();
        rl.AccountId = accountId;
        rl.ContactId = contactId;
        rl.Role_2__c = type;
        return rl;
    }
    public static Contract_Unit__c getContractUnit(String unitId) {
        Contract_Unit__c unit = new Contract_Unit__c();
        unit.External_Id__c = unitId;
        unit.Status__c = 'VEH';
        unit.Unit_Category__c = 'WOO';
        return unit;
    }
}