force-app/main/default/objects/Account/fields/Full_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Full_Billing_City__c</fullName>
    <description>Address field to use in population of standard address fields on account</description>
    <formula>Primary_Billing_Address__r.City__c</formula>
    <label>Full Billing City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Full_Billing_Country__c</fullName>
    <description>Address field to use in population of standard address fields on account</description>
    <formula>TEXT(Primary_Billing_Address__r.Country__c)</formula>
    <label>Full Billing Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Full_Billing_Postal_Code__c</fullName>
    <description>Address field to use in population of standard address fields on account</description>
    <formula>Primary_Billing_Address__r.Postal_Code__c</formula>
    <label>Full Billing Postal Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Billing_Provence__c.field-meta.xml
<CustomField>
    <fullName>Full_Billing_Provence__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Address field to use in population of standard address fields on account</description>
    <formula>TEXT(Primary_Billing_Address__r.Province__c)</formula>
    <label>Full Billing Provence</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Full_Billing_Street__c</fullName>
    <description>Full street name for primary billing</description>
    <formula>Primary_Billing_Address__r.Full_Street_Name__c</formula>
    <label>Full Billing Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Full_Shipping_City__c</fullName>
    <description>Address field to use in population of standard address fields on account</description>
    <formula>Primary_Shipping_Address__r.City__c</formula>
    <label>Full Shipping City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Full_Shipping_Country__c</fullName>
    <description>Address field to use in population of standard address fields on account</description>
    <formula>TEXT(Primary_Shipping_Address__r.Country__c)</formula>
    <label>Full Shipping Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Shipping_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Full_Shipping_Postal_Code__c</fullName>
    <description>Address field to use in population of standard address fields on account</description>
    <formula>Primary_Shipping_Address__r.Postal_Code__c</formula>
    <label>Full Shipping Postal Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Shipping_Provence__c.field-meta.xml
<CustomField>
    <fullName>Full_Shipping_Provence__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Address field to use in population of standard address fields on account</description>
    <formula>TEXT(Primary_Shipping_Address__r.Province__c)</formula>
    <label>Full Shipping Provence</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>Full_Shipping_Street__c</fullName>
    <formula>Primary_Shipping_Address__r.Full_Street_Name__c</formula>
    <label>Full Shipping Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Address__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Address at this moment</description>
    <label>Primary Billing Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Primary Billing Address for Accounts</relationshipLabel>
    <relationshipName>Primary_Billing_Address_for_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Address__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary address record</description>
    <label>Primary Shipping Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Primary Shipping Address for Accounts</relationshipLabel>
    <relationshipName>Primary_Shipping_Address_For_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique identifier used in inbound webservices</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction between account and address__c</description>
    <label>Klant Adres</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Klant Adressen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Address for this account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The relevant address record</description>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Deduplication_Key__c.field-meta.xml
<CustomField>
    <fullName>Deduplication_Key__c</fullName>
    <description>Composite key to prevent duplicates</description>
    <externalId>true</externalId>
    <label>Deduplication Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Validity of this address ends at this date</description>
    <inlineHelpText>Validity of this address ends at this date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If primary, this address will be also shown on the main account record</description>
    <inlineHelpText>If primary, this address will be also shown on the main account record</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Validity of this address starts at this date</description>
    <inlineHelpText>Validity of this address starts at this date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this Account address record. Postadres corresponds with BillingAddress and Eenheid/Woonadres with ShippingAddress on Account</description>
    <inlineHelpText>Type of this Account address record. Postadres corresponds with BillingAddress and Eenheid/Woonadres with ShippingAddress on Account</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WOO</fullName>
                <label>Woonadres</label>
            </value>
            <value>
                <fullName>POS</fullName>
                <label>Postadres</label>
            </value>
            <value>
                <fullName>BUI</fullName>
                <isActive>false</isActive>
                <label>Buitenlands adres</label>
            </value>
            <value>
                <fullName>EEN</fullName>
                <isActive>false</isActive>
                <label>EEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;NL&quot;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>House number</description>
    <inlineHelpText>House number</inlineHelpText>
    <label>House Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PO_Box_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Box_Number__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>To register the PO Box Number</description>
    <inlineHelpText>To register the PO Box Number</inlineHelpText>
    <label>PO Box Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Street name</description>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressService.cls
/**
 * Address management / utility functions
 */
public with sharing class AddressService {

    public static void setPrimaryAddressInStandardFields(Account acc) {
        acc.BillingCity = acc.Full_Billing_City__c;
        acc.BillingCountryCode = acc.Full_Billing_Country__c;
        acc.BillingPostalCode = acc.Full_Billing_Postal_Code__c;
        acc.BillingStreet = acc.Full_Billing_Street__c;
        //acc.BillingState = acc.Full_Billing_Provence__c;
        acc.ShippingCity = acc.Full_Shipping_City__c;
        acc.ShippingCountryCode = acc.Full_Shipping_Country__c;
        acc.ShippingPostalCode = acc.Full_Shipping_Postal_Code__c;
        acc.ShippingStreet = acc.Full_Shipping_Street__c;
        //acc.ShippingState = acc.Full_Shipping_Provence__c;
    }

    //
    // Retrieves all Account addresses for a uuid and returns them as PersoonAddressModel entries
    public static List<PersoonAdresModel> getPersoonAddressen(String uuid) {
        try {
            List<PersoonAdresModel> output = new List<PersoonAdresModel>();
            List<Account_Address__c> accountAddressRecords = [SELECT
                    Account__r.UUID__c, Account__r.Primary_Billing_Address__r.Unique_Key__c, Account__r.Primary_Shipping_Address__r.Unique_Key__c,
                    Address__r.Province__c, Address__r.Unique_Key__c, Address__r.Name, Address__r.PO_Box_Number__c, Address__r.Postal_Code__c,
                    Address__r.Freepost_number__c, Address__r.Street__c, Address__r.Country__c, Address__r.House_Letter__c, Address__r.Address_Line_2__c,
                    Address__r.House_Number_Addition__c, Address__r.House_Number__c, Address__r.City__c, Address__r.Address_Line_1__c, Address__r.Denotation__c,
                    Start_Date__c, End_Date__c, Is_Primary__c, Type__c, Deduplication_Key__c
                    FROM Account_Address__c
                    WHERE Account__r.UUID__c = :uuid.trim()
                    ORDER BY Start_Date__c ASC];
            for(Account_Address__c acadd : accountAddressRecords) {
                output.add(DataMapper.mapAddressToPersoonAdresModel(acadd));
            }
            return output;
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'AddressService', 'getPersoonAddressen');
            throw ex;
        }
    }

    //
    // Strips spaces from postal code
    public static void normalizePostalCodesByReference(Address__c addressRecord) {
        if(String.isEmpty(addressRecord.Postal_Code__c)) {
            return;
        }
        addressRecord.Postal_Code__c = addressRecord.Postal_Code__c.replaceAll(' ','');
    }

    //
    // Strips spaces from postal code
    public static void normalizePostalCodesByReference(AdresModel addressRecord) {
        if(String.isEmpty(addressRecord.postcode)) {
            return;
        }
        addressRecord.postcode = addressRecord.postcode.replaceAll(' ','');
    }

    //
    // Constructs a unique key value for an address record
    public static String getAddressKey(Address__c addressRecord) {
        normalizePostalCodesByReference(addressRecord);
        String country = (addressRecord.Country__c <> null) ? addressRecord.Country__c : 'NL';

        if(country<>'NL') {
            //
            // Foreign addresses can be anything
            return addressRecord.Country__c+'-'+Datetime.now().getTime();
        }
        String postalCode = (addressRecord.Postal_Code__c <> null) ? addressRecord.Postal_Code__c.trim() : '';
        String housenumber = (addressRecord.House_Number__c <> null) ? addressRecord.House_Number__c.trim() : '';
        String housenumberAddition = (addressRecord.House_Number_Addition__c <> null) ? addressRecord.House_Number_Addition__c.trim() : '';
        String houseletter = (addressRecord.House_Letter__c <> null) ? addressRecord.House_Letter__c.trim() : '';
        String poBoxNr = (addressRecord.PO_Box_Number__c <> null) ? addressRecord.PO_Box_Number__c.trim(): '';
        String antwNr = (addressRecord.Freepost_number__c <> null) ? addressRecord.Freepost_number__c.trim(): '';

        return getUniqueAddressKey(postalCode, poBoxNr, antwNr, housenumber, houseletter, housenumberAddition);
    }

    public static String getAddressKey(AdresModel addressRecord) {
        normalizePostalCodesByReference(addressRecord);
        String country = (addressRecord.land?.code <> null) ? addressRecord.land.code : 'NL';

        if(country<>'NL') {
            //
            // We don't want to make foreign addresses unique
            return null;
        }
        String postalCode = (addressRecord.postcode <> null) ? addressRecord.postcode.trim() : '';
        String housenumber = (addressRecord.huisnummer <> null) ? addressRecord.huisnummer.trim() : '';
        String housenumberAddition = (addressRecord.huisnummerToevoeging <> null) ? addressRecord.huisnummerToevoeging.trim() : '';
        String houseletter = (addressRecord.huisletter <> null) ? addressRecord.huisletter.trim() : '';
        String poBoxNr = (addressRecord.postbusnummer <> null) ? addressRecord.postbusnummer.trim(): '';
        String antwNr = (addressRecord.antwoordnummer <> null) ? addressRecord.antwoordnummer.trim(): '';

        return getUniqueAddressKey(postalCode, poBoxNr, antwNr, housenumber, houseletter, housenumberAddition);
    }

    //
    // Applies https://www.postnl.nl/Images/Brochure-KIX-code-van-PostNL_tcm10-10210.pdf
    public static String getUniqueAddressKey(String postalCode, String poBoxNr, String antwNr, String housenumber, String houseletter, String housenumberAddition) {
        String keyValue;
        //
        // This mechanism may not be the most robust,
        // perhaps a checkbox to indicate pobox/freepost addresses will be better
        // For now catch illegal combinations on the front end
        if(!String.isEmpty(poBoxNr)) {
            keyValue = postalCode+poBoxNr;

        } else if(!String.isEmpty(antwNr)) {
            keyValue = postalCode+antwNr;
        } else {
            keyValue = postalCode+housenumber+'X'+houseletter+housenumberAddition;
        }

        return keyValue;
    }

    //
    // Constructs a readable name
    public static String getNameValue(Address__c addressRecord) {
        normalizePostalCodesByReference(addressRecord);
        String country = (addressRecord.Country__c <> null) ? addressRecord.Country__c : '';
        String city = (addressRecord.City__c <> null) ? addressRecord.City__c : '';
        String street = (addressRecord.Street__c <> null) ? addressRecord.Street__c : '';
        String postalCode = (addressRecord.Postal_Code__c <> null) ? addressRecord.Postal_Code__c : '';
        String housenumber = (addressRecord.House_Number__c <> null) ? addressRecord.House_Number__c : '';
        String housenumberAddition = (!String.isEmpty(addressRecord.House_Number_Addition__c)) ? ' '+addressRecord.House_Number_Addition__c : '';
        String houseletter = (!String.isEmpty(addressRecord.House_Letter__c)) ? ' '+addressRecord.House_Letter__c : '';
        String addressLine1 = (addressRecord.Address_Line_1__c <> null) ? addressRecord.Address_Line_1__c : '';
        String addressLine2 = (addressRecord.Address_Line_2__c <> null) ? addressRecord.Address_Line_2__c : '';

        String nameValue ='';
        if(country=='NL') {
            if(!String.isBlank(addressRecord.Freepost_number__c)) {
                nameValue = 'Antwoordnummer '+addressRecord.Freepost_number__c+' '+city+', '+country;
            } else if(!String.isBlank(addressRecord.PO_Box_Number__c)) {
                nameValue = 'Postbus '+addressRecord.PO_Box_Number__c+' '+city+', '+country;

            } else {
                nameValue = street+' '+housenumber+''+houseletter+''+housenumberAddition+', '+city+', '+country;
            }
        } else {
            nameValue = addressLine1+' '+addressLine2+', '+city+', '+country;
        }
        return nameValue.abbreviate(80);
    }

    //
    // Bulk entry points
    public static List<String> getAddressKeys(List<Address__c> addresses) {
        try {
            List<String> output = new List<String>();
            for(Address__c add : addresses) {
                output.add(getAddressKey(add));
            }
            return output;
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'AddressService', 'getAddressKeys');
            throw ex;
        }
    }

    public static List<String> getNameValues(List<Address__c> addresses) {
        try {
            List<String> output = new List<String>();
            for(Address__c add : addresses) {
                output.add(getNameValue(add));
            }
            return output;
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'AddressService', 'getNameValues');
            throw ex;
        }
    }

    public static void normalizePostalCodesByReference(List<Address__c> addresses) {
        try {
            for(Address__c add : addresses) {
                normalizePostalCodesByReference(add);
            }
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'AddressService', 'normalizePostalCodesByReference(List<Address__c>)');
            throw ex;
        }
    }

    public static void normalizePostalCodesByReference(List<AdresModel> addresses) {
        try {
            for(AdresModel add : addresses) {
                normalizePostalCodesByReference(add);
            }
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'AddressService', 'normalizePostalCodesByReference(List<AdresModel>)');
            throw ex;
        }
    }

    //
    // Handles upsert of the address records and creation of the junction records
    public static List<Account_Address__c> convertPersoonAddresses(PersoonModel persoon, String uuid) {
        try {
            // Original logic unchanged
            Map<String, Address__c> addressesforUpsert = new Map<String, Address__c>();
            List<Address__c> addressesforInsert = new List<Address__c>();
            Address__c addShipping;
            Address__c addBilling;

            if(persoon.woonadres<>null) {
                addShipping = DataMapper.mapPersoonAdresToAddress(persoon.woonadres);
                if(addShipping.Unique_Key__c<> null) {
                    addressesforUpsert.put(addShipping.Unique_Key__c.toLowerCase(), addShipping);
                } else {
                    addressesforInsert.add(addShipping);
                }
            }

            if(persoon.postadres<>null) {
                addBilling = DataMapper.mapPersoonAdresToAddress(persoon.postadres);
                if(addBilling.Unique_Key__c<> null) {
                    addressesforUpsert.put(addBilling.Unique_Key__c.toLowerCase(), addBilling);
                } else {
                    addressesforInsert.add(addBilling);
                }
            }

            if(addressesforUpsert.size() > 0) {
                System.debug('#### Upserting addresses: '+JSON.serializePretty(addressesforUpsert.values()));
                upsert addressesforUpsert.values() Address__c.Unique_Key__c;
            }
            if(addressesforInsert.size() > 0) {
                System.debug('#### Inserting addresses: '+JSON.serializePretty(addressesforInsert));
                insert addressesforInsert;
            }

            Map<String, Account_Address__c> dedupeMap = new Map<String, Account_Address__c>();
            if(addShipping <> null) {
                Address__c add1 = addressesforUpsert.get(addShipping.Unique_Key__c.toLowerCase());
                Account_Address__c shippAccAddress = AddressService.getAccountAddressForUpsert(uuid, add1);
                shippAccAddress.Type__c = 'WOO';
                if(persoon.woonadres.begindatum <> null) {
                    shippAccAddress.Start_Date__c = persoon.woonadres.begindatum;
                }
                if(persoon.woonadres.einddatum <> null) {
                    shippAccAddress.End_Date__c = persoon.woonadres.einddatum;
                }
                shippAccAddress.Is_Primary__c = true;
                shippAccAddress.Deduplication_Key__c = createCompositeKey(shippAccAddress, uuid, addShipping.Unique_Key__c);
                dedupeMap.put(shippAccAddress.Deduplication_Key__c, shippAccAddress);
            }

            if(addBilling <> null) {
                Address__c add2 = addressesforUpsert.get(addBilling.Unique_Key__c.toLowerCase());
                Account_Address__c billAccAddress = AddressService.getAccountAddressForUpsert(uuid, add2);
                billAccAddress.Type__c = 'POS';
                if(persoon.postadres.begindatum <> null) {
                    billAccAddress.Start_Date__c = persoon.postadres.begindatum;
                }
                if(persoon.postadres.einddatum <> null) {
                    billAccAddress.End_Date__c = persoon.postadres.einddatum;
                }
                billAccAddress.Is_Primary__c = true;
                billAccAddress.Deduplication_Key__c = createCompositeKey(billAccAddress, uuid, addBilling.Unique_Key__c);
                dedupeMap.put(billAccAddress.Deduplication_Key__c, billAccAddress);
            }

            return dedupeMap.values();
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'AddressService', 'convertPersoonAddresses');
            throw ex;
        }
    }

    public static Account_Address__c convertPersoonAddress(PersoonAdresModel addressModel, String uuid) {
        try {
            Map<String, Address__c> addressesforUpsert = new Map<String, Address__c>();
            Address__c theAddress = DataMapper.mapPersoonAdresToAddress(addressModel);
            addressesforUpsert.put(theAddress.Unique_Key__c, theAddress);

            if(addressesforUpsert.size() > 0) {
                upsert addressesforUpsert.values() Address__c.Unique_Key__c;
            }

            Account_Address__c accAddress = AddressService.getAccountAddressForUpsert(uuid, theAddress);
            accAddress.Start_Date__c = addressModel.begindatum;
            accAddress.End_Date__c = addressModel.einddatum;
            accAddress.Type__c = addressModel.soort.code;
            accAddress.Deduplication_Key__c = createCompositeKey(accAddress, uuid, theAddress.Unique_Key__c);
            return accAddress;
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'AddressService', 'convertPersoonAddress');
            throw ex;
        }
    }

    @TestVisible
    private static Account_Address__c getAccountAddressForUpsert(String accountUuid, Address__c addressRecord) {
        System.assertNotEquals(null, addressRecord?.Id, 'Address needs an id');
        System.assertNotEquals(null, accountUuid, 'UUID mandatory');
        Account_Address__c accAd = new Account_Address__c();
        accAd.Address__c = addressRecord.Id;
        accAd.Account__r = new Account(UUID__c=accountUuid);
        accAd.Is_Primary__c = true;
        return accAd;
    }

    private static String createCompositeKey(Account_Address__c input, String personUuid, String addressId) {
        String output = personUuid+'-'+addressId+'-'+IdentifierService.getDateStamp(input.Start_Date__c)+'-'+input.Type__c;
        return output;
    }

    //
    // For bulk/trigger use. Fills by reference
    public static void fillCompositeKeys(List<Account_Address__c> adds) {
        try {
            Set<ID> accIds = new Set<ID>();
            for(Account_Address__c aa : adds) {
                accIds.add(aa.Account__c);
            }
            Set<ID> addressIds = new Set<ID>();
            for(Account_Address__c aa : adds) {
                addressIds.add(aa.Address__c);
            }
            Map<ID, Account> accMap = new Map<ID, Account>([SELECT Id, UUID__c FROM Account WHERE Id IN :accIds]);
            Map<ID, Address__c> addrMap = new Map<ID, Address__c>([SELECT Id, Unique_Key__c FROM Address__c WHERE Id IN :addressIds]);
            for(Account_Address__c aa : adds) {
                if(String.isEmpty(aa.Deduplication_Key__c)) {
                    String uuid = accMap.get(aa.Account__c)?.UUID__c;
                    String addId = addrMap.get(aa.Address__c)?.Unique_Key__c;
                    aa.Deduplication_Key__c = createCompositeKey(aa, uuid, addId);
                }
            }
        } catch (Exception ex) {
            ApexFaultHandler.publishError(ex, 'AddressService', 'fillCompositeKeys');
            throw ex;
        }
    }
}