force-app/main/default/objects/Account/fields/Primary_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Address__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary address record</description>
    <label>Primary Shipping Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Primary Shipping Address for Accounts</relationshipLabel>
    <relationshipName>Primary_Shipping_Address_For_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique identifier used in inbound webservices</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction between account and address__c</description>
    <label>Klant Adres</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Klant Adressen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Address for this account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The relevant address record</description>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Deduplication_Key__c.field-meta.xml
<CustomField>
    <fullName>Deduplication_Key__c</fullName>
    <description>Composite key to prevent duplicates</description>
    <externalId>true</externalId>
    <label>Deduplication Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PersoonAdressenRestServiceTest.cls
@IsTest
private class PersoonAdressenRestServiceTest {
    @TestSetup
    private static void setupData() {
        //
        // Needs a mock response, since flow may trigger outbound call
        Test.setMock(HttpCalloutMock.class, new OkapiMocks.GetRelationSuccess());

        insert TestDataFactory.getPersonAccounts(1);
        Account acc = [SELECT UUID__c FROM Account]; // Returns 1 account
        String uuid = acc.UUID__c;
        List<Address__c> addresses = TestDataFactory.getAddresses(2);
        upsert addresses Address__c.Unique_Key__c;
        List<Account_Address__c> accAddresses = new List<Account_Address__c>();
        accAddresses.add(AddressService.getAccountAddressForUpsert(uuid, addresses[0]));
        accAddresses.add(AddressService.getAccountAddressForUpsert(uuid, addresses[1]));
        upsert accAddresses;
        acc.Primary_Shipping_Address__c=addresses[0].Id;
        acc.Primary_Shipping_Address__c=addresses[1].Id;
        update acc;
    }
    @IsTest
    static void testGet200() {

        Account acc = [SELECT UUID__c FROM Account]; // Returns 1 account
        String uuid = acc.UUID__c;
        Test.startTest();
        RestResponse resp = PersoonAdressenRestService.testGetCall(uuid);
        Test.stopTest();
        RestServiceResponse respResponse = (RestServiceResponse) JSON.deserialize(resp.responseBody.toString(), RestServiceResponse.class);
        System.assertEquals(2, respResponse.addresses.size(),'Expected 2 addresses for this Account');
        System.assertEquals(200, resp.statusCode,'Expected 200 http code');
    }
    @IsTest
    static void testGet404() {
        Test.startTest();
        RestResponse resp = PersoonAdressenRestService.testGetCall('nonsense');
        Test.stopTest();
        RestServiceResponse respResponse = (RestServiceResponse) JSON.deserialize(resp.responseBody.toString(), RestServiceResponse.class);
        System.assertEquals(null, respResponse.addresses,'Expected no addresses for this uuid');
        System.assertEquals(404, resp.statusCode,'Expected 404 http code');
    }
    @IsTest
    static void testGet400() {

        Test.startTest();
        RestResponse resp = PersoonAdressenRestService.testGetCall(null);
        Test.stopTest();
        RestServiceResponse respResponse = (RestServiceResponse) JSON.deserialize(resp.responseBody.toString(), RestServiceResponse.class);
        System.assertEquals(null, respResponse.addresses,'Expected no addresses for this uuid');
        System.assertEquals('No resource requested; uuid parameter is mandatory', respResponse.errors[0],'Expected error about missing uuid');
        System.assertEquals(400, resp.statusCode,'Expected 400 http code');
    }
    @IsTest
    static void testPost201() {
        //
        // Needs a mock response, since flow may trigger outbound call
        Test.setMock(HttpCalloutMock.class, new OkapiMocks.GetRelationSuccess());

        Account acc = [SELECT UUID__c FROM Account]; // Returns 1 account
        String uuid = acc.UUID__c;
        PersoonAdresModel pa = PersoonAdresModel.getMock(uuid);
        pa.idPersoon = uuid;
        //
        // Identical address, should not result in extra Account Address record
        PersoonAdresModel pa2 = PersoonAdresModel.getMock(uuid);
        pa2.idPersoon = uuid;
        Test.startTest();
        RestResponse resp = PersoonAdressenRestService.testPostCall(pa);
        RestResponse resp2= PersoonAdressenRestService.testPostCall(pa2);
        Test.stopTest();
        List<Account_Address__c> accAddresses = [SELECT Id, Deduplication_Key__c FROM Account_Address__c WHERE Account__r.UUID__c=:uuid];
        System.Debug('### 201: '+JSON.serializePretty(accAddresses));
        List<Address__c> addr = [SELECT Id FROM Address__c];
        System.assertEquals(3, addr.size(),'Expected a new address, 3 in total now');
        System.assertEquals(2, accAddresses.size(),'Expected a new account address, 3 in total now');
        //
        // Modified address, should result in extra Account Address record
        PersoonAdresModel pa3 = PersoonAdresModel.getMock(uuid);
        pa3.idPersoon = uuid;
        pa3.adres.postcode = '5555ZZ';
        RestResponse resp3 = PersoonAdressenRestService.testPostCall(pa3);
        List<Address__c> addr2 = [SELECT Id FROM Address__c];
        List<Account_Address__c> accAddresses2 = [SELECT Id, Deduplication_Key__c FROM Account_Address__c WHERE Account__r.UUID__c=:uuid];
        System.assertEquals(4, addr2.size(),'Expected a new address, 4 in total now');
        System.assertEquals(2, accAddresses2.size(),'Expected a new account address, 4 in total now');
    }
    @IsTest
    static void testPost400() {
        Test.startTest();
        RestResponse resp = PersoonAdressenRestService.testPostCall(null);
        Test.stopTest();
        RestServiceResponse respResponse = (RestServiceResponse) JSON.deserialize(resp.responseBody.toString(), RestServiceResponse.class);
        System.assertEquals(400, resp.statusCode,'Expected 404 http code');
        System.assertEquals(1, respResponse.errors.size(),'Expected 1 error');
    }
}