force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique identifier used in inbound webservices</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Role_2__c.field-meta.xml
<CustomField>
    <fullName>Role_2__c</fullName>
    <description>Different Account Contact Relationship roles that can exist between an Account and a Contact</description>
    <inlineHelpText>What Account Contact Relationship roles can exist between an Account and a Contact?</inlineHelpText>
    <label>Role Relation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPE</fullName>
                <label>Contactpersoon</label>
            </value>
            <value>
                <fullName>MDW</fullName>
                <label>Medewerker</label>
            </value>
            <value>
                <fullName>BEH</fullName>
                <isActive>false</isActive>
                <label>Beheerder</label>
            </value>
            <value>
                <fullName>BSL</fullName>
                <isActive>false</isActive>
                <label>Bestuurslid</label>
            </value>
            <value>
                <fullName>Bewindgevoerde</fullName>
                <isActive>false</isActive>
                <label>Bewindgevoerde</label>
            </value>
            <value>
                <fullName>EIG</fullName>
                <isActive>false</isActive>
                <label>MVE Eigenaar</label>
            </value>
            <value>
                <fullName>PEN</fullName>
                <isActive>false</isActive>
                <label>Penningmeester</label>
            </value>
            <value>
                <fullName>SEC</fullName>
                <isActive>false</isActive>
                <label>Secretaris</label>
            </value>
            <value>
                <fullName>VVL</fullName>
                <isActive>false</isActive>
                <label>VVE-lid</label>
            </value>
            <value>
                <fullName>VOO</fullName>
                <isActive>false</isActive>
                <label>Voorzitter</label>
            </value>
            <value>
                <fullName>Werkgever</fullName>
                <isActive>false</isActive>
                <label>Werkgever</label>
            </value>
            <value>
                <fullName>WOL</fullName>
                <isActive>false</isActive>
                <label>Wooncommissie lid</label>
            </value>
            <value>
                <fullName>COL</fullName>
                <isActive>false</isActive>
                <label>Wooncoöperatielid</label>
            </value>
            <value>
                <fullName>ccc</fullName>
                <isActive>false</isActive>
                <label>ccc</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Subsidiary_Relation__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Relation__c</fullName>
    <complianceGroup>GDPR (Salesforce Id)</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Subsidiary personaccount or contact in this relation</description>
    <label>Subsidiary Relation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships (Subsidiary Relation)</relationshipLabel>
    <relationshipName>Subsidiary_Account_In_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PersonRelationServiceTest.cls
/**
 * Created by harm on 02/09/2024.
 */
@IsTest
private class PersonRelationServiceTest {
    @IsTest
    private static void testAccountContactRelations() {
        PersoonModel pm = PersoonModel.getMock();
        pm.persoonRelaties[0].relatieRol.code = 'CPE'; // this role should exist in AccountContactRelation
        pm.persoonRelaties.add(PersoonRelatieModel.getMock('mock-id')); // Add a role that should not end up in AccountContactRelation
        //System.debug('## '+JSON.serializePretty(pm));
        Test.startTest();
        List<AccountContactRelation> rels = PersonRelationService.getAccountContactRelationRecordsForUpsert(pm, 'mock-id');
        System.assertEquals(1, rels.size(), 'Expected 1 record');
        System.assert(rels[0].Role_2__c.contains('CPE'), 'Expected CPE role: '+rels[0].Role_2__c);
        Test.stopTest();
    }
    @IsTest
    private static void testRelationships() {
        PersoonModel pm = PersoonModel.getMock();
        pm.persoonRelaties[0].relatieRol.code = 'BWI'; // this role should exist in Relationship__c
        pm.persoonRelaties.add(PersoonRelatieModel.getMock('mock-id')); // Add a role that should not end up in Relationship__c
        Test.startTest();
        List<Relationship__c> rels = PersonRelationService.getRelationshipRecordsForUpsert(pm, 'mock-id');
        System.assertEquals(1, rels.size(), 'Expected 1 record');
        System.assertEquals('BWI',rels[0].Type__c, 'Expected BWI type');
        Test.stopTest();
    }
    @IsTest
    private static void testTriggers() {
        Account[] accs = TestDataFactory.getPersonAccounts(2);
        accs[0].UUID__c = '1234';
        accs[1].UUID__c = '2234';
        upsert accs;
        Relationship__c rel = new Relationship__c();
        rel.Type__c = 'BWI';
        rel.Primary_Relation__r = new Account(UUID__c='1234');
        rel.Subsidiary_Relation__r = new Account(UUID__c='2234');
        AccountContactRelation rel2 = new AccountContactRelation();
        rel2.Role_2__c = 'CPE';
        rel2.Account = new Account(UUID__c='1234');
        rel2.Contact = new Contact(Contact_UUID__c='2234');
        Test.startTest();
        upsert rel;
        upsert rel2;
        System.assertNotEquals(null, rel.Id,'Expected ID in Relationship__c');
        System.assertNotEquals(null, rel2.Id,'Expected ID in AccountContactRelation');
        Test.stopTest();
    }
}