force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction between account and address__c</description>
    <label>Klant Adres</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Klant Adressen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Address for this account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The relevant address record</description>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If primary, this address will be also shown on the main account record</description>
    <inlineHelpText>If primary, this address will be also shown on the main account record</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Validity of this address starts at this date</description>
    <inlineHelpText>Validity of this address starts at this date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of this Account address record. Postadres corresponds with BillingAddress and Eenheid/Woonadres with ShippingAddress on Account</description>
    <inlineHelpText>Type of this Account address record. Postadres corresponds with BillingAddress and Eenheid/Woonadres with ShippingAddress on Account</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WOO</fullName>
                <label>Woonadres</label>
            </value>
            <value>
                <fullName>POS</fullName>
                <label>Postadres</label>
            </value>
            <value>
                <fullName>BUI</fullName>
                <isActive>false</isActive>
                <label>Buitenlands adres</label>
            </value>
            <value>
                <fullName>EEN</fullName>
                <isActive>false</isActive>
                <label>EEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;NL&quot;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>House number</description>
    <inlineHelpText>House number</inlineHelpText>
    <label>House Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Street name</description>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/woonstadTestMockClasses.cls
/*************************************************************************************************
 * Test Class      : woonstadTestMockClasses
 * Layer           : Test Support
 * Purpose         : Mock classes for testing woonstad services
 * Security        : @isTest annotation
 * Owner           : Woonstad KC
 * Last Modified   : 2025-01-27
 *************************************************************************************************/
@isTest
public class woonstadTestMockClasses {
    
    /**
     * @description Test data factory for creating test records
     */
    public static List<Account> createTestAccounts(Integer count) {
        List<Account> accounts = new List<Account>();
        
        for(Integer i = 0; i < count; i++) {
            Account acc = new Account(
                Name = 'Test Account ' + i,
                Phone = '555-000' + i,
                BillingStreet = 'Test Street ' + i,
                BillingCity = 'Test City',
                BillingPostalCode = '1000' + i,
                BillingCountry = 'Netherlands'
            );
            accounts.add(acc);
        }
        
        return accounts;
    }
    
    public static List<Address__c> createTestAddresses(Integer count) {
        List<Address__c> addresses = new List<Address__c>();
        
        for(Integer i = 0; i < count; i++) {
            Address__c addr = new Address__c(
                Street__c = 'Test Street ' + i,
                Postal_Code__c = '100' + i + ' AB',
                House_Number__c = String.valueOf(i + 1),
                House_Letter__c = null,
                House_Number_Addition__c = null,
                Country__c = 'Netherlands',
                City__c = 'Test City ' + i,
                BAG_Id__c = 'BAG' + String.valueOf(1000000 + i),
                Address_Line_1__c = 'Test Street ' + i + ' ' + (i + 1)
            );
            addresses.add(addr);
        }
        
        return addresses;
    }
    
    public static List<Account_Address__c> createTestLinks(
        List<Account> accounts, 
        List<Address__c> addresses
    ) {
        List<Account_Address__c> links = new List<Account_Address__c>();
        
        Integer maxLinks = Math.min(accounts.size(), addresses.size());
        
        for(Integer i = 0; i < maxLinks; i++) {
            Account_Address__c link = new Account_Address__c(
                Account__c = accounts[i].Id,
                Address__c = addresses[i].Id,
                Is_Primary__c = (i == 0),
                Start_Date__c = Date.today().addDays(-i),
                Type__c = 'WOO'
            );
            links.add(link);
        }
        
        return links;
    }
}